### ISSUE TITLE
thread.isAlive() : no attr isAlive

### ISSUE THREAD

**Issue by tamwile** [Gorfiend/TsuboDB#1]
`python tsubodb.py --scan`
```python
Traceback (most recent call last):
  File "/path/to/TsuboDB/tsubodb.py", line 267, in <module>
    main()
  File "/path/to/TsuboDB/tsubodb.py", line 148, in main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/hashlib.py", line 160, in __hash_new
    for file in db.get_local_files(files):
  File "/path/to/TsuboDB/tsubodb/localdb.py", line 117, in get_local_files
    return _hashlib.new(name, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_hashlib.UnsupportedDigestmodError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    for h in hashed_files:
  File "/path/to/TsuboDB/tsubodb/hash.py", line 78, in hash_files
    self.run()
  File "/path/to/TsuboDB/tsubodb/hash.py", line 66, in run
    while hashlist or any([thread.isAlive() for thread in threads]):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/TsuboDB/tsubodb/hash.py", line 78, in <listcomp>
    self.hashlist.append(HashedFile(f))
                         ^^^^^^^^^^^^^
  File "/path/to/TsuboDB/tsubodb/hash.py", line 52, in __init__
    while hashlist or any([thread.isAlive() for thread in threads]):
                           ^^^^^^^^^^^^^^
AttributeError: 'Hashthread' object has no attribute 'isAlive'. Did you mean: 'is_alive'?
```

**Comment by Gorfiend** [comment]
Pushed a change that fixes this, and also (hopefully) an issue with md4 hash being disabled.

**Comment by tamwile** [comment]
Thank you for the fix.
